### ISSUE TITLE
maven issue

### ISSUE THREAD

**Issue by a-nand** [graphqly/vertx-graphql-client#1]
`<dependency>
    <groupId>io.github.graphqly</groupId>
    <artifactId>vertx-graphql-client</artifactId>
    <version>0.1.0</version
</dependency>`

This does not resolve. Am I missing anything?

**Comment by anhldbk** [comment]
@a-nand Please wait. I'm publishing the package now

**Comment by anhldbk** [comment]
@a-nand The package is ready. Please double check ;) 

https://mvnrepository.com/artifact/io.github.graphqly/vertx-graphql-client
