### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by EchedeyLR** [graphqly/vertx-graphql-client#2]
I wanted to know if this project is under a license or not. I am interested in using it but I am worried about that part.

**Comment by anhldbk** [comment]
Hey @EchedeyLR, thank you for using this lib. Just updated. The license is Apache 2.0.

**Comment by EchedeyLR** [comment]
Thank you for creating the project, I was looking for a client lib to make requests to a GraphQL API and this was the easier and best documented app to use for the use case I wanted.

Other bigger and more supported libs didn't explain my use case and were more complex to use as well as dedicated to create and test APIs, not just a client.

It was my first time having to deal with GraphQL too.

I think I can close the issue already.
